-- ============================================================================
-- V001 - Identity & RBAC (03-DB §5, §38.1; conventions §3)
--
-- Conventions applied everywhere:
--   * UUID primary keys generated by the application (03-DB §3.1)
--   * TIMESTAMPTZ stored in UTC (03-DB §3.2)
--   * created_at/created_by/updated_at/updated_by audit columns (03-DB §3.4);
--     *_by is NULL when the change was made by the system or a seed script
--   * version BIGINT for optimistic locking (03-DB §28)
--   * status columns are VARCHAR + CHECK so a value can be added with a plain
--     migration instead of an ALTER TYPE on a PostgreSQL enum
-- ============================================================================

CREATE TABLE users (
    id             UUID PRIMARY KEY,
    username       VARCHAR(100) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    password_hash  VARCHAR(255) NOT NULL,
    display_name   VARCHAR(255) NOT NULL,
    status         VARCHAR(30)  NOT NULL CHECK (status IN ('ACTIVE', 'LOCKED', 'DISABLED')),
    last_login_at  TIMESTAMPTZ NULL,
    deleted_at     TIMESTAMPTZ NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by     UUID NULL,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by     UUID NULL,
    version        BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email    UNIQUE (email)
);
CREATE INDEX idx_users_status ON users (status);

COMMENT ON TABLE  users               IS 'Local accounts (01-SRS FR-IAM-01). Only a password hash is stored (03-DB §30).';
COMMENT ON COLUMN users.status        IS 'ACTIVE | LOCKED (admin lock, sessions revoked) | DISABLED (03-DB §5.1)';
COMMENT ON COLUMN users.password_hash IS 'DelegatingPasswordEncoder format, e.g. {bcrypt}$2a$10$... (D-04)';

CREATE TABLE roles (
    id          UUID PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description TEXT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by  UUID NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by  UUID NULL,
    version     BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_roles_code UNIQUE (code)
);
COMMENT ON TABLE roles IS 'RBAC roles are data, not code: ADMIN / COORDINATOR / ENGINEER are seeded (03-DB §5.2).';

CREATE TABLE permissions (
    id       UUID PRIMARY KEY,
    code     VARCHAR(100) NOT NULL,
    resource VARCHAR(100) NOT NULL,
    action   VARCHAR(50)  NOT NULL,
    CONSTRAINT uk_permissions_code UNIQUE (code)
);
COMMENT ON TABLE  permissions      IS 'Reference data; code = "<resource>.<action>" and is used verbatim in @PreAuthorize (04-API §4, D-06).';

CREATE TABLE user_roles (
    user_id UUID NOT NULL REFERENCES users (id),
    role_id UUID NOT NULL REFERENCES roles (id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE role_permissions (
    role_id       UUID NOT NULL REFERENCES roles (id),
    permission_id UUID NOT NULL REFERENCES permissions (id),
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE user_sessions (
    id               UUID PRIMARY KEY,
    user_id          UUID NOT NULL REFERENCES users (id),
    session_key_hash VARCHAR(255) NOT NULL,
    ip_address       VARCHAR(64) NULL,
    user_agent       TEXT NULL,
    expires_at       TIMESTAMPTZ NOT NULL,
    revoked_at       TIMESTAMPTZ NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_user_sessions_key UNIQUE (session_key_hash)
);
CREATE INDEX idx_user_sessions_user ON user_sessions (user_id, revoked_at);
COMMENT ON TABLE user_sessions IS 'One row per login; its id travels in the JWT "sid" claim so logout/lock can revoke access immediately (D-03).';

CREATE TABLE refresh_tokens (
    id             UUID PRIMARY KEY,
    user_id        UUID NOT NULL REFERENCES users (id),
    session_id     UUID NOT NULL REFERENCES user_sessions (id),
    token_hash     VARCHAR(255) NOT NULL,
    expires_at     TIMESTAMPTZ NOT NULL,
    revoked_at     TIMESTAMPTZ NULL,
    replaced_by_id UUID NULL REFERENCES refresh_tokens (id),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash)
);
CREATE INDEX idx_refresh_tokens_session ON refresh_tokens (session_id);
COMMENT ON TABLE  refresh_tokens                IS 'Opaque refresh tokens stored only as SHA-256 hashes and rotated on every use (D-02, 03-DB §38.1).';
COMMENT ON COLUMN refresh_tokens.replaced_by_id IS 'Rotation chain: reuse of a token that already has a successor means theft -> revoke the session.';

CREATE TABLE login_attempts (
    id                UUID PRIMARY KEY,
    username_or_email VARCHAR(255) NOT NULL,
    user_id           UUID NULL REFERENCES users (id),
    success           BOOLEAN NOT NULL,
    failure_reason    VARCHAR(100) NULL,
    ip_address        VARCHAR(64) NULL,
    occurred_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_login_attempts_login_time ON login_attempts (username_or_email, occurred_at DESC);
COMMENT ON TABLE login_attempts IS 'Every login attempt, successful or not; the base rate limit (5 failures / 15 min, D-09) is computed from this table.';
