-- ============================================================================
-- V007 - Service Catalog (01-SRS §4; 03-DB §7 + canonical §38.2; 04-API §5;
--        blueprint D-32 .. D-36)
--
-- services             : what OpsCenter monitors. services.code is the join key
--                        with the Prometheus label service=<code> (FR-ALT-05), so
--                        it is lower case and immutable (D-33).
-- service_environments : DEV / STAGING / PRODUCTION rows of a service. Endpoints
--                        (health, metrics, dashboard) differ per environment, which
--                        is why they live here and not on services (03-DB §38.2).
-- service_owners       : ADDITIONAL owners. The "main" owners are the three columns
--                        on services (owning team, primary + backup user). Each row
--                        points to exactly one team OR one user (D-34).
--
-- Conventions of the base (blueprint base §5): UUID ids generated by the
-- application, TIMESTAMPTZ, VARCHAR + CHECK instead of PostgreSQL enums, audit
-- columns + optimistic-lock version, soft delete = is_active/deleted_at.
-- ============================================================================

CREATE TABLE services (
    id               UUID PRIMARY KEY,
    organization_id  UUID         NOT NULL REFERENCES organizations (id),
    code             VARCHAR(100) NOT NULL,
    name             VARCHAR(255) NOT NULL,
    description      TEXT         NULL,
    status           VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE'
                     CHECK (status IN ('ACTIVE', 'DEGRADED', 'MAINTENANCE')),
    owning_team_id   UUID         NULL REFERENCES teams (id),
    primary_owner_id UUID         NULL REFERENCES users (id),
    backup_owner_id  UUID         NULL REFERENCES users (id),
    metadata         JSONB        NULL,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    deleted_at       TIMESTAMPTZ  NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by       UUID         NULL,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by       UUID         NULL,
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_services_org_code         UNIQUE (organization_id, code),
    CONSTRAINT ck_services_code_format      CHECK (code ~ '^[a-z0-9][a-z0-9._-]{0,99}$'),
    CONSTRAINT ck_services_owners_differ    CHECK (primary_owner_id IS NULL OR backup_owner_id IS NULL
                                                   OR primary_owner_id <> backup_owner_id),
    CONSTRAINT ck_services_deleted_inactive CHECK (deleted_at IS NULL OR is_active = FALSE)
);
CREATE INDEX idx_services_team       ON services (owning_team_id);
CREATE INDEX idx_services_status     ON services (status);
CREATE INDEX idx_services_org_active ON services (organization_id, is_active, code);

COMMENT ON TABLE  services                  IS 'Service Catalog (01-SRS §4, 03-DB §7.1). Environment-specific endpoints live in service_environments (03-DB §38.2).';
COMMENT ON COLUMN services.code             IS 'Join key with the Prometheus label service=<code> (FR-ALT-05); lower case, immutable (D-33).';
COMMENT ON COLUMN services.owning_team_id   IS 'Main owning team (01-SRS §4); additional owners are rows of service_owners (D-34).';
COMMENT ON COLUMN services.metadata         IS 'Free-form descriptive JSON (<= 8 KB, no credentials - 03-DB §30).';

CREATE TABLE service_environments (
    id               UUID PRIMARY KEY,
    service_id       UUID         NOT NULL REFERENCES services (id),
    environment_code VARCHAR(50)  NOT NULL CHECK (environment_code ~ '^[A-Z][A-Z0-9_]{1,49}$'),
    status           VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE'
                     CHECK (status IN ('ACTIVE', 'DEGRADED', 'MAINTENANCE')),
    health_endpoint  VARCHAR(500) NULL,
    metric_endpoint  VARCHAR(500) NULL,
    dashboard_url    VARCHAR(500) NULL,
    metadata         JSONB        NULL,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    deleted_at       TIMESTAMPTZ  NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by       UUID         NULL,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by       UUID         NULL,
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_service_env                  UNIQUE (service_id, environment_code),
    CONSTRAINT ck_service_env_deleted_inactive CHECK (deleted_at IS NULL OR is_active = FALSE)
);
CREATE INDEX idx_service_env_service ON service_environments (service_id);
CREATE INDEX idx_service_env_status  ON service_environments (status);

COMMENT ON TABLE  service_environments                  IS 'One row per (service, environment) - 03-DB §38.2 canonical model (D-32).';
COMMENT ON COLUMN service_environments.environment_code IS 'Canonical upper case DEV / STAGING / PRODUCTION; aliases PROD, STG ... are normalised by the application (D-33).';

CREATE TABLE service_owners (
    id             UUID PRIMARY KEY,
    service_id     UUID        NOT NULL REFERENCES services (id),
    team_id        UUID        NULL REFERENCES teams (id),
    user_id        UUID        NULL REFERENCES users (id),
    ownership_type VARCHAR(50) NOT NULL
                   CHECK (ownership_type IN ('SUPPORTING_TEAM', 'TECHNICAL_OWNER', 'BUSINESS_OWNER', 'ON_CALL_CONTACT')),
    priority       INT         NOT NULL DEFAULT 1 CHECK (priority BETWEEN 1 AND 100),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by     UUID        NULL,
    CONSTRAINT ck_service_owners_one_target CHECK (num_nonnulls(team_id, user_id) = 1)
);
CREATE UNIQUE INDEX uk_service_owners_team ON service_owners (service_id, team_id, ownership_type) WHERE team_id IS NOT NULL;
CREATE UNIQUE INDEX uk_service_owners_user ON service_owners (service_id, user_id, ownership_type) WHERE user_id IS NOT NULL;
CREATE INDEX idx_service_owners_team ON service_owners (team_id);
CREATE INDEX idx_service_owners_user ON service_owners (user_id);

COMMENT ON TABLE service_owners IS 'Additional owners of a service; exactly one of team_id/user_id (D-34). Replaced as a whole by PUT /services/{id}/ownership (D-35); history is in audit_logs.';
